name: Sync Branch
on:
  push:
    branches:
      - 'staging-demo'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge staging-demo > deploy-staging
        uses: devmasx/merge-branch@v1.3.1
        with: 
          type: now
          from_branch: staging-demo
          target_branch: deploy-staging
          github_token: ${{ github.token }}
